### ISSUE TITLE
The ontology highligths is not working

### ISSUE THREAD

**Issue by ypriverol** [OmicsDI/index-pipeline#15]
The ontology highlights are not working properly properly.

**Comment by ypriverol** [comment]
The pipeline is not running because some dataset do not contains synonyms..

**Comment by mindcrusher11** [comment]
pipeline is running but it pride instead of Pride so I updated it and it is working now

**Comment by ypriverol** [comment]
Is this working in PRoduction?

**Comment by mindcrusher11** [comment]
yes it is

**Comment by mindcrusher11** [comment]
shall I close this

**Comment by mindcrusher11** [comment]
https://www.omicsdi.org/dataset/pride/PXD001861
